sozluk = {
    "hello": "merhaba",
    "goodbye": "hoşça kal",
    "thank you": "teşekkür ederim",
    "yes": "evet",
    "no": "hayır",
    "please": "lütfen",
    "excuse me": "affedersiniz",
    "sorry": "üzgünüm",
    "I": "ben",
    "you": "sen/siz" "good: iyi",
    "bad": "kötü",
    "happy": "mutlu",
    "sad": "üzgün",
    "nice": "güzel",
    "ugly": "çirkin",
    "big": "büyük",
    "small": "küçük",
    "old": "eski",
    "new": "yeni",
    "hot": "sıcak",
    "cold": "soğuk",
    "easy": "kolay",
    "difficult": "zor",
    "slow": "yavaş",
    "fast": "hızlı",
    "right": "doğru",
    "wrong": "yanlış",
    "true": "doğru",
    "false": "yanlış",
    "first": "ilk",
    "last": "son",
    "open": "aç",
    "close": "kapat",
    "start": "başlat",
    "finish": "bitir",
    "go": "git",
    "come": "gel",
    "stop": "dur",
    "wait": "bekle",
    "see": "gör",
    "hear": "duy",
    "speak": "konuş",
    "listen": "dinle",
    "read": "oku",
    "write": "yaz",
    "learn": "öğren",
    "understand": "anla",
    "know": "bil",
    "remember": "hatırla",
    "forget": "unut",
    "want": "iste",
    "need": "ihtiyaç duy",
    "have": "sahip ol",
    "give": "ver",
    "take": "al",
    "buy": "satın al",
    "sell": "sat",
    "eat": "ye",
    "drink": "iç",
    "sleep": "uyku",
    "wake up": "uyan",
    "run": "koş",
    "walk": "yürü",
    "stand": "dur",
    "sit": "otur",
    "drive": "sür",
    "fly": "uç",
    "swim": "yüz",
    "work": "çalış",
    "play": "oyna",
    "sing": "şarkı söyle",
    "dance": "dans et",
    "draw": "çiz",
    "paint": "boya",
    "cook": "pişir",
    "bake": "fırında pişir",
    "clean": "temizle",
    "wash": "yıka",
    "brush": "fırçala",
    "comb": "tarayıcı",
    "cut": "kes",
    "break": "kır",
    "fix": "tamir et",
    "help": "yardım et",
    "love": "sev",
    "hate": "nefret et",
    "like": "hoşlan",
    "dislike": "hoşlanma",
    "enjoy": "keyif al",
    "understand": "anla",
    "believe": "inan",
    "doubt": "şüphe duy",
    "hope": "umut et",
    "fear": "kork",
    "trust": "güven",
    "respect": "saygı göster",
    "apologize": "özür dile",
    "thank": "teşekkür et",
    "excuse": "mazur gör",
    "meet": "tanış",
    "friend": "arkadaş",
    "family": "aile",
    "brother": "erkek kardeş",
    "sister": "kız kardeş",
    "mother": "anne",
    "father": "baba",
    "son": "oğul",
    "daughter": "kız",
    "baby": "bebek",
    "achieve": "başarmak",
    "advantage": "avantaj",
    "analysis": "analiz",
    "behavior": "davranış",
    "benefit": "fayda",
    "challenge": "zorluk",
    "circumstance": "durum",
    "community": "topluluk",
    "competition": "rekabet",
    "condition": "koşul",
    "connection": "bağlantı",
    "consequence": "sonuç",
    "cooperation": "işbirliği",
    "courage": "cesaret",
    "creativity": "yaratıcılık",
    "decision": "karar",
    "definition": "tanım",
    "development": "gelişim",
    "discovery": "keşif",
    "efficiency": "verimlilik",
    "emotion": "duygu",
    "energy": "enerji",
    "environment": "çevre",
    "equality": "eşitlik",
    "experience": "deneyim",
    "experiment": "deney",
    "expression": "ifade",
    "failure": "başarısızlık",
    "focus": "odaklanma",
    "freedom": "özgürlük",
    "friendship": "arkadaşlık",
    "growth": "büyüme",
    "happiness": "mutluluk",
    "improvement": "gelişim",
    "information": "bilgi",
    "innovation": "yenilik",
    "inspiration": "ilham",
    "knowledge": "bilgi",
    "leadership": "liderlik",
    "learning": "öğrenme",
    "mistake": "hata",
    "motivation": "motivasyon",
    "opportunity": "fırsat",
    "passion": "tutku",
    "perseverance": "azim",
    "potential": "potansiyel",
    "problem": "sorun",
    "progress": " ilerleme",
    "purpose": "amaç",
    "quality": " kalite",
    "relationship": "ilişki",
    "resilience": "direnç",
    "resource": "kaynak",
    "responsibility": "sorumluluk",
    "risk": "risk",
    "satisfaction": "memnuniyet",
    "skill": "beceri",
    "solution": "çözüm",
    "strategy": "strateji",
    "strength": "güç",
    "success": "başarı",
    "support": "destek",
    "teamwork": "işbirliği",
    "technology": "teknoloji",
    "trust": "güven",
    "understanding": "anlayış",
    "value": "değer",
    "vision": "vizyon",
    "wisdom": "bilgelik",
    "adaptability": "uyum sağlama",
    "ambition": "hırs",
    "commitment": "bağlılık",
    "communication": "iletişim",
    "dedication": "özveri",
    "discipline": "disiplin",
    "empathy": "empati",
    "flexibility": "esneklik",
    "gratitude": "minnettarlık",
    "integrity": "dürüstlük",
    "patience": "sabır",
    "perseverance": "azim",
    "respect": "saygı",
    "self-confidence": "özgüven",
    "self-discipline": "öz disiplin",
    "self-improvement": " kendini geliştirme",
    "self-motivation": "kendini motive etme",
    "self-awareness": "öz farkındalık",
    "self-esteem": "öz saygı",
    "self-reflection": "öz değerlendirme",
    "time management": "zaman yönetimi",
    "critical thinking": "eleştirel düşünme",
    "problem-solving": "problem çözme",
    "decision-making": "karar verme",
    "effective communication": "etkili iletişim",
    "leadership skills": "liderlik becerileri",
    "teamwork skills": "takım çalışması becerileri",
    "adaptability skills": "uyum sağlama becerileri",
    "resilience skills": "dayanıklılık becerileri",
    "creative thinking": "yaratıcı düşünme",
    "emotional intelligence": "duygusal zeka",
}

kelime = input("İngilizce bir kelime girin: ").lower()

if kelime in sozluk:
    ceviri = sozluk[kelime]
    print(f"{kelime} kelimesinin Türkçe çevirisi: {ceviri}")
else:
    print("Bu kelimenin çevirisi bulunamadı.")
